//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by ResXFileCodeGenerator. Visual Studio regenerates this file
//     when Strings.resx changes. Manual edits may be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookGreenlight.AddIn.Resources
{
    using System;
    using System.Globalization;
    using System.Resources;

    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class Strings
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Strings() { }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan is null)
                {
                    var temp = new ResourceManager("OutlookGreenlight.AddIn.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string Get(string key) => ResourceManager.GetString(key, resourceCulture) ?? key;

        internal static string App_Name => Get(nameof(App_Name));
        internal static string Ribbon_GroupLabel => Get(nameof(Ribbon_GroupLabel));
        internal static string Ribbon_ButtonLabel => Get(nameof(Ribbon_ButtonLabel));
        internal static string Ribbon_ButtonSupertip => Get(nameof(Ribbon_ButtonSupertip));
        internal static string RoomPicker_Title => Get(nameof(RoomPicker_Title));
        internal static string RoomPicker_Header => Get(nameof(RoomPicker_Header));
        internal static string RoomPicker_Loading => Get(nameof(RoomPicker_Loading));
        internal static string RoomPicker_NoRooms => Get(nameof(RoomPicker_NoRooms));
        internal static string RoomPicker_InsertButton => Get(nameof(RoomPicker_InsertButton));
        internal static string RoomPicker_CancelButton => Get(nameof(RoomPicker_CancelButton));
        internal static string Login_Title => Get(nameof(Login_Title));
        internal static string Meeting_Header => Get(nameof(Meeting_Header));
        internal static string Meeting_Room => Get(nameof(Meeting_Room));
        internal static string Meeting_JoinLinkText => Get(nameof(Meeting_JoinLinkText));
        internal static string Error_NoAppointmentContext => Get(nameof(Error_NoAppointmentContext));
        internal static string Error_NoGreenlightUrl => Get(nameof(Error_NoGreenlightUrl));
        internal static string Error_LoadRooms => Get(nameof(Error_LoadRooms));
        internal static string Error_Unexpected => Get(nameof(Error_Unexpected));
    }
}
