//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by Visual Studio Tools for Office. Do not modify.
//     This file will be regenerated when the VSTO project is opened in VS.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookGreenlight.AddIn
{
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.Outlook.OutlookAddIn
    {
        public ThisAddIn(Microsoft.Office.Tools.Outlook.Factory factory, System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            InternalStartup();
        }
    }

    partial class ThisAddInHost
    {
        public static ThisAddIn AddIn
        {
            get { return Globals.ThisAddIn; }
        }
    }

    internal sealed partial class Globals
    {
        private Globals() { }

        private static ThisAddIn _ThisAddIn;

        internal static ThisAddIn ThisAddIn
        {
            get { return _ThisAddIn; }
            set
            {
                if (_ThisAddIn == null)
                    _ThisAddIn = value;
                else
                    throw new System.NotSupportedException();
            }
        }

        internal static Microsoft.Office.Tools.Outlook.Factory Factory { get; set; }
    }
}
