# Creates the local self-signed code-signing certificate used for VSTO
# manifest signing and optional Authenticode signing of the DLL/MSI.
#
# Defaults are intentionally local-dev friendly: private key in CurrentUser\My,
# trust in CurrentUser Root/TrustedPublisher, and only the thumbprint written
# to the gitignored Directory.Build.local.props.

[CmdletBinding()]
param(
    [string]$CommonName = 'Greenroom Connector Dev Signing',

    [string]$Organization = '',

    [string]$OrganizationalUnit = '',

    [string]$Country = '',

    [string]$EmailAddress = '',

    [string]$Subject = '',

    [switch]$IncludeEmailInSubject,

    [switch]$NoEmailSan,

    [ValidateRange(1, 50)]
    [int]$Years = 10,

    [ValidateRange(0, 3650)]
    [int]$ReuseMinValidDays = 30,

    [string]$CertificateType = 'CodeSigningCert',

    [string]$CertificateStoreLocation = 'Cert:\CurrentUser\My',

    [string[]]$TrustStoreLocations = @(
        'Cert:\CurrentUser\Root',
        'Cert:\CurrentUser\TrustedPublisher'
    ),

    [string]$CodeSigningEkuOid = '1.3.6.1.5.5.7.3.3',

    [string]$EmailSanOid = '2.5.29.17',

    [string]$KeyAlgorithm = 'RSA',

    [int]$KeyLength = 3072,

    [string]$HashAlgorithm = 'SHA256',

    [string]$KeyUsage = 'DigitalSignature',

    [ValidateSet('Exportable', 'NonExportable')]
    [string]$KeyExportPolicy = 'NonExportable',

    [string[]]$TextExtension = @(),

    [string]$LocalPropsPath = (Join-Path $PSScriptRoot '..\Directory.Build.local.props'),

    [string]$LocalPropsPropertyName = 'GrcSigningCertificateThumbprint',

    [string]$GeneratedComment = 'Generated by scripts\New-SigningCertificate.ps1. Do not commit.',

    [switch]$ForceNew,

    [switch]$SkipTrust
)

$ErrorActionPreference = 'Stop'

function Format-X500AttributeValue {
    param([string]$Value)

    if ($null -eq $Value) {
        return ''
    }

    $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    if ($escaped -match '[,+"\\<>;=]' -or $escaped.StartsWith(' ') -or $escaped.EndsWith(' ')) {
        return '"' + $escaped + '"'
    }

    return $escaped
}

function New-SubjectFromParts {
    param(
        [string]$Cn,
        [string]$Org,
        [string]$Ou,
        [string]$CountryCode,
        [string]$Email,
        [bool]$WithEmail
    )

    $parts = [System.Collections.Generic.List[string]]::new()

    if ($Cn) { $parts.Add("CN=$(Format-X500AttributeValue $Cn)") }
    if ($Org) { $parts.Add("O=$(Format-X500AttributeValue $Org)") }
    if ($Ou) { $parts.Add("OU=$(Format-X500AttributeValue $Ou)") }
    if ($CountryCode) { $parts.Add("C=$(Format-X500AttributeValue $CountryCode)") }
    if ($WithEmail -and $Email) { $parts.Add("E=$(Format-X500AttributeValue $Email)") }

    if ($parts.Count -eq 0) {
        throw 'At least one subject field is required. Pass -Subject or set -CommonName/-Organization.'
    }

    return ($parts -join ', ')
}

function ConvertTo-CertEnrollSubject {
    param([string]$DistinguishedName)

    # CertEnroll treats "+" as an RDN separator in unquoted attribute values.
    # If callers pass an unquoted E=/EMAILADDRESS= value with "+", quote it.
    return [regex]::Replace(
        $DistinguishedName,
        '(?i)(^|,\s*)(E|EMAILADDRESS)=([^",][^,]*\+[^,]*)',
        { param($match) "$($match.Groups[1].Value)$($match.Groups[2].Value)=`"$($match.Groups[3].Value)`"" }
    )
}

function Test-CodeSigningCertificate {
    param(
        [System.Security.Cryptography.X509Certificates.X509Certificate2]$Certificate,
        [string]$EkuOid
    )

    foreach ($eku in $Certificate.EnhancedKeyUsageList) {
        if ($eku.ObjectId.Value -eq $EkuOid) {
            return $true
        }
    }

    return $false
}

function Import-TrustCertificate {
    param(
        [System.Security.Cryptography.X509Certificates.X509Certificate2]$Certificate,
        [string]$StoreLocation
    )

    $existing = Get-ChildItem -Path $StoreLocation -ErrorAction SilentlyContinue |
        Where-Object { $_.Thumbprint -eq $Certificate.Thumbprint } |
        Select-Object -First 1

    if ($existing) {
        return
    }

    $tempFile = Join-Path ([System.IO.Path]::GetTempPath()) "$($Certificate.Thumbprint).cer"
    try {
        Export-Certificate -Cert $Certificate -FilePath $tempFile | Out-Null
        Import-Certificate -FilePath $tempFile -CertStoreLocation $StoreLocation | Out-Null
    } finally {
        Remove-Item -LiteralPath $tempFile -ErrorAction SilentlyContinue
    }
}

function Write-LocalProps {
    param(
        [string]$Path,
        [string]$PropertyName,
        [string]$Thumbprint,
        [string]$Comment
    )

    $resolvedPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
    $content = @"
<Project>
  <!-- $Comment -->
  <PropertyGroup>
    <$PropertyName>$Thumbprint</$PropertyName>
  </PropertyGroup>
</Project>
"@

    Set-Content -LiteralPath $resolvedPath -Value $content -Encoding UTF8
}

$now = Get-Date
$expires = $now.AddYears($Years)
$rawSubject = if ($Subject) {
    $Subject
} else {
    New-SubjectFromParts `
        -Cn $CommonName `
        -Org $Organization `
        -Ou $OrganizationalUnit `
        -CountryCode $Country `
        -Email $EmailAddress `
        -WithEmail $IncludeEmailInSubject.IsPresent
}
$certSubject = ConvertTo-CertEnrollSubject -DistinguishedName $rawSubject
$cert = $null

if (-not $ForceNew) {
    $cert = Get-ChildItem -Path $CertificateStoreLocation |
        Where-Object {
            ($_.Subject -eq $rawSubject -or $_.Subject -eq $certSubject) -and
            $_.HasPrivateKey -and
            $_.NotAfter -gt $now.AddDays($ReuseMinValidDays) -and
            (Test-CodeSigningCertificate -Certificate $_ -EkuOid $CodeSigningEkuOid)
        } |
        Sort-Object NotAfter -Descending |
        Select-Object -First 1
}

if (-not $cert) {
    $extensions = @($TextExtension)
    if (-not $NoEmailSan -and $EmailAddress) {
        $extensions += "$EmailSanOid={text}email=$EmailAddress"
    }

    $certificateArgs = @{
        Type = $CertificateType
        Subject = $certSubject
        CertStoreLocation = $CertificateStoreLocation
        KeyAlgorithm = $KeyAlgorithm
        KeyLength = $KeyLength
        HashAlgorithm = $HashAlgorithm
        KeyUsage = $KeyUsage
        KeyExportPolicy = $KeyExportPolicy
        NotAfter = $expires
    }

    if ($extensions.Count -gt 0) {
        $certificateArgs.TextExtension = $extensions
    }

    $cert = New-SelfSignedCertificate @certificateArgs
}

if (-not $SkipTrust) {
    foreach ($storeLocation in $TrustStoreLocations) {
        Import-TrustCertificate -Certificate $cert -StoreLocation $storeLocation
    }
}

Write-LocalProps `
    -Path $LocalPropsPath `
    -PropertyName $LocalPropsPropertyName `
    -Thumbprint $cert.Thumbprint `
    -Comment $GeneratedComment

Write-Host "Signing certificate ready." -ForegroundColor Green
Write-Host "Subject:    $($cert.Subject)"
if (-not $NoEmailSan -and $EmailAddress) { Write-Host "Email SAN:  $EmailAddress" }
Write-Host "Thumbprint: $($cert.Thumbprint)"
Write-Host "Expires:    $($cert.NotAfter.ToString('yyyy-MM-dd'))"
Write-Host "Store:      $CertificateStoreLocation"
if (-not $SkipTrust) { Write-Host "Trusted in: $($TrustStoreLocations -join ', ')" }
Write-Host "Local MSBuild props: $($ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($LocalPropsPath))"
