//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by ResXFileCodeGenerator. Visual Studio regenerates this file
//     when Strings.resx changes. Manual edits may be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenroomConnector.Resources
{
    using System;
    using System.Globalization;
    using System.Resources;

    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class Strings
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Strings() { }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan is null)
                {
                    var temp = new ResourceManager("GreenroomConnector.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string Get(string key) => ResourceManager.GetString(key, resourceCulture) ?? key;

        internal static string App_Name => Get(nameof(App_Name));
        internal static string Ribbon_GroupLabel => Get(nameof(Ribbon_GroupLabel));
        internal static string Ribbon_ButtonLabel => Get(nameof(Ribbon_ButtonLabel));
        internal static string Ribbon_ButtonSupertip => Get(nameof(Ribbon_ButtonSupertip));
        internal static string Ribbon_SignOutLabel => Get(nameof(Ribbon_SignOutLabel));
        internal static string Ribbon_SignOutSupertip => Get(nameof(Ribbon_SignOutSupertip));
        internal static string SignOut_DoneMessage => Get(nameof(SignOut_DoneMessage));
        internal static string SignOut_LocalOnlyMessage => Get(nameof(SignOut_LocalOnlyMessage));
        internal static string RoomPicker_Title => Get(nameof(RoomPicker_Title));
        internal static string RoomPicker_Header => Get(nameof(RoomPicker_Header));
        internal static string RoomPicker_Loading => Get(nameof(RoomPicker_Loading));
        internal static string RoomPicker_NoRooms => Get(nameof(RoomPicker_NoRooms));
        internal static string RoomPicker_InsertButton => Get(nameof(RoomPicker_InsertButton));
        internal static string RoomPicker_CancelButton => Get(nameof(RoomPicker_CancelButton));
        internal static string RoomPicker_NewRoomButton => Get(nameof(RoomPicker_NewRoomButton));
        internal static string RoomPicker_InsertAsModeratorButton => Get(nameof(RoomPicker_InsertAsModeratorButton));
        internal static string RoomPicker_CheckingModeratorCode => Get(nameof(RoomPicker_CheckingModeratorCode));
        internal static string CreateRoom_Title => Get(nameof(CreateRoom_Title));
        internal static string CreateRoom_NameLabel => Get(nameof(CreateRoom_NameLabel));
        internal static string CreateRoom_SettingsGroup => Get(nameof(CreateRoom_SettingsGroup));
        internal static string CreateRoom_Record => Get(nameof(CreateRoom_Record));
        internal static string CreateRoom_RequireAuth => Get(nameof(CreateRoom_RequireAuth));
        internal static string CreateRoom_AnyoneModerator => Get(nameof(CreateRoom_AnyoneModerator));
        internal static string CreateRoom_ViewerCode => Get(nameof(CreateRoom_ViewerCode));
        internal static string CreateRoom_ModeratorCode => Get(nameof(CreateRoom_ModeratorCode));
        internal static string CreateRoom_GuestPolicy => Get(nameof(CreateRoom_GuestPolicy));
        internal static string CreateRoom_GuestAlways => Get(nameof(CreateRoom_GuestAlways));
        internal static string CreateRoom_GuestAsk => Get(nameof(CreateRoom_GuestAsk));
        internal static string CreateRoom_GuestDeny => Get(nameof(CreateRoom_GuestDeny));
        internal static string CreateRoom_SubmitButton => Get(nameof(CreateRoom_SubmitButton));
        internal static string CreateRoom_LoadingConfig => Get(nameof(CreateRoom_LoadingConfig));
        internal static string CreateRoom_ConfigError => Get(nameof(CreateRoom_ConfigError));
        internal static string Login_Title => Get(nameof(Login_Title));
        internal static string Logout_Title => Get(nameof(Logout_Title));
        internal static string Meeting_Header => Get(nameof(Meeting_Header));
        internal static string Meeting_Room => Get(nameof(Meeting_Room));
        internal static string Meeting_JoinLinkText => Get(nameof(Meeting_JoinLinkText));
        internal static string Meeting_DialIn => Get(nameof(Meeting_DialIn));
        internal static string Error_NoAppointmentContext => Get(nameof(Error_NoAppointmentContext));
        internal static string Error_NoGreenlightUrl => Get(nameof(Error_NoGreenlightUrl));
        internal static string Error_LoadRooms => Get(nameof(Error_LoadRooms));
        internal static string Error_Unexpected => Get(nameof(Error_Unexpected));
    }
}
